//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-09/29/2005 11:56 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.31 at 01:32:53 AM PDT 
//


package org.uniprot.uniprot;


/**
 * Java content class for nameListType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/dondi/Downloads/xsd2db/uniprot/xsd//uniprot.xsd line 241)
 * <p>
 * <pre>
 * &lt;complexType name="nameListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="person" type="{http://uniprot.org/uniprot}personType"/>
 *         &lt;element name="consortium" type="{http://uniprot.org/uniprot}consortiumType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface NameListType {


    /**
     * Gets the value of the PersonOrConsortium property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the PersonOrConsortium property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonOrConsortium().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.uniprot.uniprot.NameListType.Person}
     * {@link org.uniprot.uniprot.NameListType.Consortium}
     * 
     */
    java.util.List getPersonOrConsortium();

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Long}
     */
    java.lang.Long getHjid();

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Long}
     */
    void setHjid(java.lang.Long value);

    /**
     * Gets the value of the hjversion property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Long}
     */
    java.lang.Long getHjversion();

    /**
     * Sets the value of the hjversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Long}
     */
    void setHjversion(java.lang.Long value);


    /**
     * Java content class for consortium element declaration.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/dondi/Downloads/xsd2db/uniprot/xsd//uniprot.xsd line 244)
     * <p>
     * <pre>
     * &lt;element name="consortium" type="{http://uniprot.org/uniprot}consortiumType"/>
     * </pre>
     * 
     */
    public interface Consortium
        extends javax.xml.bind.Element, org.uniprot.uniprot.ConsortiumType
    {


    }


    /**
     * Java content class for person element declaration.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/dondi/Downloads/xsd2db/uniprot/xsd//uniprot.xsd line 243)
     * <p>
     * <pre>
     * &lt;element name="person" type="{http://uniprot.org/uniprot}personType"/>
     * </pre>
     * 
     */
    public interface Person
        extends javax.xml.bind.Element, org.uniprot.uniprot.PersonType
    {


    }

}
